# Generated by Django 5.0.7 on 2025-09-28 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UMLDiagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('diagram_type', models.CharField(choices=[('CLASS', 'Class Diagram'), ('SEQUENCE', 'Sequence Diagram'), ('USE_CASE', 'Use Case Diagram'), ('ACTIVITY', 'Activity Diagram'), ('STATE', 'State Diagram'), ('COMPONENT', 'Component Diagram'), ('DEPLOYMENT', 'Deployment Diagram')], default='CLASS', max_length=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('DEPRECATED', 'Deprecated')], default='DRAFT', max_length=15)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('TEAM', 'Team'), ('ORGANIZATION', 'Organization'), ('PUBLIC', 'Public')], default='TEAM', max_length=15)),
                ('diagram_data', models.JSONField(default=dict, help_text='Complete UML diagram structure and elements')),
                ('layout_config', models.JSONField(default=dict, help_text='Diagram layout and presentation configuration')),
                ('validation_results', models.JSONField(default=dict, help_text='Latest validation results and architectural recommendations')),
                ('tags', models.JSONField(default=list, help_text='Searchable tags for diagram categorization')),
                ('metadata', models.JSONField(default=dict, help_text='Additional diagram metadata and custom fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_template', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_diagrams', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_diagrams', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Owner of the UML diagram', on_delete=django.db.models.deletion.CASCADE, related_name='uml_diagrams', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_diagrams', to='uml_diagrams.umldiagram')),
            ],
            options={
                'db_table': 'uml_diagrams',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UMLClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('package', models.CharField(blank=True, max_length=500)),
                ('class_type', models.CharField(choices=[('CLASS', 'Class'), ('ABSTRACT_CLASS', 'Abstract Class'), ('INTERFACE', 'Interface'), ('ENUM', 'Enumeration'), ('RECORD', 'Record')], default='CLASS', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public (+)'), ('PRIVATE', 'Private (-)'), ('PROTECTED', 'Protected (#)'), ('PACKAGE', 'Package (~)')], default='PUBLIC', max_length=10)),
                ('is_abstract', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('is_static', models.BooleanField(default=False)),
                ('stereotype', models.CharField(blank=True, max_length=100)),
                ('documentation', models.TextField(blank=True)),
                ('attributes', models.JSONField(default=list)),
                ('methods', models.JSONField(default=list)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=120.0)),
                ('height', models.FloatField(default=80.0)),
                ('style_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_classes', to=settings.AUTH_USER_MODEL)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='uml_diagrams.umldiagram')),
            ],
            options={
                'db_table': 'uml_classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiagramVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('diagram_data', models.JSONField(help_text='Complete diagram state at this version')),
                ('layout_config', models.JSONField(default=dict, help_text='Layout configuration at this version')),
                ('change_summary', models.TextField(help_text='Summary of changes in this version')),
                ('change_details', models.JSONField(default=dict, help_text='Detailed change information for diff generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_major_version', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, help_text='Version tag or label', max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagram_versions', to=settings.AUTH_USER_MODEL)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='uml_diagrams.diagramversion')),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='uml_diagrams.umldiagram')),
            ],
            options={
                'db_table': 'diagram_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='UMLRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('relationship_type', models.CharField(choices=[('ASSOCIATION', 'Association'), ('AGGREGATION', 'Aggregation'), ('COMPOSITION', 'Composition'), ('INHERITANCE', 'Inheritance'), ('REALIZATION', 'Realization'), ('DEPENDENCY', 'Dependency'), ('GENERALIZATION', 'Generalization')], default='ASSOCIATION', max_length=20)),
                ('source_multiplicity', models.CharField(choices=[('0..1', '0..1'), ('1', '1'), ('0..*', '0..*'), ('1..*', '1..*'), ('*', '*')], default='1', max_length=10)),
                ('target_multiplicity', models.CharField(choices=[('0..1', '0..1'), ('1', '1'), ('0..*', '0..*'), ('1..*', '1..*'), ('*', '*')], default='1', max_length=10)),
                ('source_role', models.CharField(blank=True, max_length=100)),
                ('target_role', models.CharField(blank=True, max_length=100)),
                ('source_navigable', models.BooleanField(default=True)),
                ('target_navigable', models.BooleanField(default=True)),
                ('documentation', models.TextField(blank=True)),
                ('stereotype', models.CharField(blank=True, max_length=100)),
                ('style_config', models.JSONField(default=dict)),
                ('path_points', models.JSONField(default=list, help_text='Connection path points for visual representation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_relationships', to=settings.AUTH_USER_MODEL)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='uml_diagrams.umldiagram')),
                ('source_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='uml_diagrams.umlclass')),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='uml_diagrams.umlclass')),
            ],
            options={
                'db_table': 'uml_relationships',
                'ordering': ['name', 'relationship_type'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('NAMING_CONVENTION', 'Naming Convention'), ('ARCHITECTURAL_PATTERN', 'Architectural Pattern'), ('DESIGN_PRINCIPLE', 'Design Principle'), ('CODE_QUALITY', 'Code Quality'), ('SECURITY', 'Security'), ('PERFORMANCE', 'Performance')], default='DESIGN_PRINCIPLE', max_length=25)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Information'), ('SUGGESTION', 'Suggestion')], default='WARNING', max_length=15)),
                ('rule_pattern', models.JSONField(help_text='Pattern definition for rule matching')),
                ('validation_logic', models.TextField(help_text='Python code for validation logic')),
                ('error_message', models.CharField(max_length=500)),
                ('suggestion', models.TextField(blank=True)),
                ('applicable_diagrams', models.JSONField(default=list, help_text='Diagram types this rule applies to')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_rule', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_validation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validation_rules',
                'ordering': ['rule_type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='umldiagram',
            index=models.Index(fields=['owner', 'diagram_type'], name='uml_diagram_owner_i_2952f1_idx'),
        ),
        migrations.AddIndex(
            model_name='umldiagram',
            index=models.Index(fields=['created_by', 'created_at'], name='uml_diagram_created_95595c_idx'),
        ),
        migrations.AddIndex(
            model_name='umldiagram',
            index=models.Index(fields=['status', 'updated_at'], name='uml_diagram_status_b67e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='umldiagram',
            index=models.Index(fields=['name', 'owner'], name='uml_diagram_name_ef3117_idx'),
        ),
        migrations.AddIndex(
            model_name='umldiagram',
            index=models.Index(fields=['is_template', 'diagram_type'], name='uml_diagram_is_temp_fa9ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='umlclass',
            index=models.Index(fields=['diagram', 'name'], name='uml_classes_diagram_b7131a_idx'),
        ),
        migrations.AddIndex(
            model_name='umlclass',
            index=models.Index(fields=['class_type', 'diagram'], name='uml_classes_class_t_bcb660_idx'),
        ),
        migrations.AddIndex(
            model_name='umlclass',
            index=models.Index(fields=['package', 'name'], name='uml_classes_package_de3992_idx'),
        ),
        migrations.AddConstraint(
            model_name='umlclass',
            constraint=models.UniqueConstraint(fields=('diagram', 'name', 'package'), name='unique_class_per_diagram'),
        ),
        migrations.AddIndex(
            model_name='diagramversion',
            index=models.Index(fields=['diagram', 'version_number'], name='diagram_ver_diagram_4a9733_idx'),
        ),
        migrations.AddIndex(
            model_name='diagramversion',
            index=models.Index(fields=['created_by', 'created_at'], name='diagram_ver_created_8a4161_idx'),
        ),
        migrations.AddIndex(
            model_name='diagramversion',
            index=models.Index(fields=['is_major_version', 'diagram'], name='diagram_ver_is_majo_6973fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagramversion',
            constraint=models.UniqueConstraint(fields=('diagram', 'version_number'), name='unique_version_per_diagram'),
        ),
        migrations.AddIndex(
            model_name='umlrelationship',
            index=models.Index(fields=['diagram', 'relationship_type'], name='uml_relatio_diagram_6cd28f_idx'),
        ),
        migrations.AddIndex(
            model_name='umlrelationship',
            index=models.Index(fields=['source_class', 'target_class'], name='uml_relatio_source__91b21a_idx'),
        ),
        migrations.AddIndex(
            model_name='umlrelationship',
            index=models.Index(fields=['relationship_type', 'diagram'], name='uml_relatio_relatio_9b7f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrule',
            index=models.Index(fields=['rule_type', 'is_active'], name='validation__rule_ty_1e0599_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrule',
            index=models.Index(fields=['severity', 'is_active'], name='validation__severit_6f6c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrule',
            index=models.Index(fields=['is_system_rule', 'rule_type'], name='validation__is_syst_6149f5_idx'),
        ),
    ]
