# Generated by Django 5.0.7 on 2025-09-28 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uml_diagrams', '0001_initial_refactored'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='umldiagram',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow public access without authentication'),
        ),
        migrations.AddField(
            model_name='umldiagram',
            name='public_edit_url',
            field=models.UUIDField(blank=True, editable=False, help_text='Unique URL for public editing access', null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='umldiagram',
            index=models.Index(fields=['is_public', 'visibility'], name='uml_diagram_is_publ_473221_idx'),
        ),
        migrations.AddIndex(
            model_name='umldiagram',
            index=models.Index(fields=['public_edit_url'], name='uml_diagram_public__1dba27_idx'),
        ),
    ]
