# Generated by Django 5.0.7 on 2025-09-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uml_diagrams', '0003_anonymous_diagrams'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='umldiagram',
            new_name='uml_diagram_session_615b88_idx',
            old_name='uml_diagrams_session_created_idx',
        ),
        migrations.RenameIndex(
            model_name='umldiagram',
            new_name='uml_diagram_created_702097_idx',
            old_name='uml_diagrams_created_idx',
        ),
        migrations.RenameIndex(
            model_name='umldiagram',
            new_name='uml_diagram_last_mo_3c415e_idx',
            old_name='uml_diagrams_modified_idx',
        ),
        migrations.RenameIndex(
            model_name='umldiagram',
            new_name='uml_diagram_diagram_eb91f9_idx',
            old_name='uml_diagrams_type_idx',
        ),
    ]
