# Generated by Django 5.0.7 on 2025-09-20 02:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Workspace name (3-255 characters)', max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255)])),
                ('slug', models.SlugField(help_text='URL-friendly workspace identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Workspace description and purpose', max_length=1000, null=True)),
                ('workspace_type', models.CharField(choices=[('PERSONAL', 'Personal Workspace'), ('TEAM', 'Team Workspace'), ('ORGANIZATION', 'Organization Workspace'), ('ENTERPRISE', 'Enterprise Workspace')], default='PERSONAL', help_text='Type of workspace determining features and limits', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='Current workspace status', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Workspace-specific configuration settings')),
                ('max_projects', models.PositiveIntegerField(default=5, help_text='Maximum number of projects allowed in workspace')),
                ('max_members_per_project', models.PositiveIntegerField(default=10, help_text='Maximum members allowed per project')),
                ('max_diagrams_per_project', models.PositiveIntegerField(default=50, help_text='Maximum diagrams allowed per project')),
                ('max_storage_mb', models.PositiveIntegerField(default=1000, help_text='Maximum storage in MB for workspace')),
                ('enable_real_time_collaboration', models.BooleanField(default=True, help_text='Enable real-time collaborative editing')),
                ('enable_version_control', models.BooleanField(default=True, help_text='Enable diagram version control')),
                ('enable_code_generation', models.BooleanField(default=True, help_text='Enable SpringBoot code generation')),
                ('enable_api_access', models.BooleanField(default=False, help_text='Enable API access for integrations')),
                ('enable_advanced_templates', models.BooleanField(default=False, help_text='Enable advanced code generation templates')),
                ('current_projects', models.PositiveIntegerField(default=0, help_text='Current number of active projects')),
                ('total_diagrams', models.PositiveIntegerField(default=0, help_text='Total number of diagrams across all projects')),
                ('total_generations', models.PositiveIntegerField(default=0, help_text='Total number of code generations performed')),
                ('storage_used_mb', models.PositiveIntegerField(default=0, help_text='Current storage usage in MB')),
                ('subscription_plan', models.CharField(default='FREE', help_text='Current subscription plan', max_length=50)),
                ('billing_email', models.EmailField(blank=True, help_text='Email for billing notifications', max_length=254, null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, help_text='When current subscription expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Workspace owner with full administrative rights', on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'db_table': 'projects_workspace',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name (3-255 characters)', max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255)])),
                ('slug', models.SlugField(help_text='URL-friendly template identifier', max_length=100)),
                ('description', models.TextField(help_text='Detailed template description and use cases', max_length=2000)),
                ('short_description', models.CharField(help_text='Brief template description for listings', max_length=500)),
                ('template_type', models.CharField(choices=[('SYSTEM', 'System Template'), ('ORGANIZATION', 'Organization Template'), ('USER', 'User Template'), ('COMMUNITY', 'Community Template')], default='USER', help_text='Template type and visibility scope', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Current template status', max_length=20)),
                ('category', models.CharField(choices=[('WEB_APPLICATION', 'Web Application'), ('MICROSERVICE', 'Microservice'), ('REST_API', 'REST API'), ('ENTERPRISE_APP', 'Enterprise Application'), ('PROTOTYPE', 'Prototype'), ('EDUCATIONAL', 'Educational'), ('CUSTOM', 'Custom')], default='CUSTOM', help_text='Template category for organization', max_length=30)),
                ('project_config', models.JSONField(default=dict, help_text='Default project configuration for this template')),
                ('springboot_config', models.JSONField(default=dict, help_text='Default SpringBoot configuration for this template')),
                ('uml_template_data', models.JSONField(blank=True, default=dict, help_text='Initial UML diagram template data')),
                ('code_generation_settings', models.JSONField(blank=True, default=dict, help_text='Code generation configuration and preferences')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Template tags for categorization and search')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='Technologies and frameworks used in this template')),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='Prerequisites and requirements for using template')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times template has been used')),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='Number of likes/favorites')),
                ('downloads_count', models.PositiveIntegerField(default=0, help_text='Number of downloads/exports')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, help_text='Average user rating (0.00-5.00)', max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0, help_text='Number of ratings received')),
                ('version', models.CharField(default='1.0.0', help_text='Template version (semantic versioning)', max_length=20)),
                ('readme_content', models.TextField(blank=True, help_text='Template documentation in Markdown', null=True)),
                ('changelog', models.TextField(blank=True, help_text='Version changelog and update history', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether template is publicly accessible')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether template is featured in listings')),
                ('requires_approval', models.BooleanField(default=False, help_text='Whether template usage requires approval')),
                ('published_at', models.DateTimeField(blank=True, help_text='When template was published', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time template was used to create project', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Template author', on_delete=django.db.models.deletion.CASCADE, related_name='authored_templates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_templates', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, help_text='Parent template if this is a derived version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_templates', to='projects.projecttemplate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_templates', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, help_text='Workspace that owns this template (for organization templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='projects.workspace')),
            ],
            options={
                'verbose_name': 'Project Template',
                'verbose_name_plural': 'Project Templates',
                'db_table': 'projects_project_template',
                'ordering': ['-is_featured', '-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project name (3-255 characters)', max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255)])),
                ('description', models.TextField(blank=True, help_text='Project description and objectives', max_length=2000, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('SUSPENDED', 'Suspended'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='Current project status', max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('TEAM', 'Team Only'), ('ORGANIZATION', 'Organization'), ('PUBLIC', 'Public')], default='PRIVATE', help_text='Project visibility and access level', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Project-specific configuration settings')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional project metadata and tags')),
                ('springboot_config', models.JSONField(blank=True, default=dict, help_text='SpringBoot code generation configuration')),
                ('max_collaborators', models.PositiveIntegerField(default=10, help_text='Maximum number of concurrent collaborators')),
                ('auto_save_interval', models.PositiveIntegerField(default=30, help_text='Auto-save interval in seconds')),
                ('enable_real_time_collaboration', models.BooleanField(default=True, help_text='Enable real-time collaborative editing')),
                ('enable_version_control', models.BooleanField(default=True, help_text='Enable diagram version control')),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last project activity')),
                ('diagram_count', models.PositiveIntegerField(default=0, help_text='Total number of diagrams in project')),
                ('generation_count', models.PositiveIntegerField(default=0, help_text='Total number of code generations performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Project owner with full administrative rights', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Parent workspace containing this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.workspace')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects_project',
                'ordering': ['-last_activity_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('VIEWER', 'Viewer'), ('EDITOR', 'Editor'), ('DEVELOPER', 'Developer'), ('ADMIN', 'Administrator'), ('OWNER', 'Owner')], default='VIEWER', help_text="Member's role and permissions level", max_length=20)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REMOVED', 'Removed'), ('LEFT', 'Left')], default='INVITED', help_text='Current membership status', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Custom permissions override for this member')),
                ('invited_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation was sent')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='Last time member was active in project', null=True)),
                ('collaboration_sessions', models.PositiveIntegerField(default=0, help_text='Number of collaboration sessions participated in')),
                ('diagrams_created', models.PositiveIntegerField(default=0, help_text='Number of diagrams created by this member')),
                ('diagrams_edited', models.PositiveIntegerField(default=0, help_text='Number of diagrams edited by this member')),
                ('code_generations', models.PositiveIntegerField(default=0, help_text='Number of code generations performed by this member')),
                ('joined_at', models.DateTimeField(blank=True, help_text='When member actively joined the project', null=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='When member left the project', null=True)),
                ('rejoined_at', models.DateTimeField(blank=True, help_text='When member rejoined after leaving', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who invited this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(help_text='User who is a member of the project', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': 'Project Members',
                'db_table': 'projects_project_member',
                'ordering': ['-joined_at', '-accepted_at', '-invited_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='projects_pr_project_c23615_idx'), models.Index(fields=['user', 'status'], name='projects_pr_user_id_2a665e_idx'), models.Index(fields=['project', 'role', 'status'], name='projects_pr_project_bee19b_idx'), models.Index(fields=['invited_by'], name='projects_pr_invited_ca0780_idx'), models.Index(fields=['last_activity_at'], name='projects_pr_last_ac_3d3d31_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_user_membership'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', 'status'], name='projects_wo_owner_i_5f4878_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['workspace_type', 'status'], name='projects_wo_workspa_7590b7_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['slug'], name='projects_wo_slug_e35a95_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['subscription_plan'], name='projects_wo_subscri_47b02c_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['created_at'], name='projects_wo_created_4d6163_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.CheckConstraint(check=models.Q(('max_projects__gte', 1), ('max_projects__lte', 1000)), name='valid_max_projects_range'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.CheckConstraint(check=models.Q(('max_members_per_project__gte', 1), ('max_members_per_project__lte', 100)), name='valid_max_members_range'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.CheckConstraint(check=models.Q(('storage_used_mb__gte', 0), ('storage_used_mb__lte', models.F('max_storage_mb'))), name='valid_storage_usage'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['template_type', 'status'], name='projects_pr_templat_222d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['category', 'status'], name='projects_pr_categor_086994_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['author', 'status'], name='projects_pr_author__e92c97_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['workspace', 'status'], name='projects_pr_workspa_6a0f52_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['is_public', 'status'], name='projects_pr_is_publ_4d5e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['is_featured', 'status'], name='projects_pr_is_feat_5a681a_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['usage_count'], name='projects_pr_usage_c_50da3f_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['rating_average'], name='projects_pr_rating__f1fd06_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['created_at'], name='projects_pr_created_a9eeba_idx'),
        ),
        migrations.AddConstraint(
            model_name='projecttemplate',
            constraint=models.UniqueConstraint(fields=('slug', 'author'), name='unique_template_slug_per_author'),
        ),
        migrations.AddConstraint(
            model_name='projecttemplate',
            constraint=models.CheckConstraint(check=models.Q(('rating_average__gte', 0.0), ('rating_average__lte', 5.0)), name='valid_rating_range'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'status'], name='projects_pr_owner_i_4798b7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'status'], name='projects_pr_workspa_944c68_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'visibility'], name='projects_pr_status_393468_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['last_activity_at'], name='projects_pr_last_ac_93a3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('max_collaborators__gte', 1), ('max_collaborators__lte', 100)), name='valid_max_collaborators_range'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('auto_save_interval__gte', 5), ('auto_save_interval__lte', 300)), name='valid_auto_save_interval_range'),
        ),
    ]
