# Generated by Django 5.0.7 on 2025-09-13 03:34

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('corporate_email', models.EmailField(help_text='Corporate email address used for authentication', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('full_name', models.CharField(help_text='Full name of the employee', max_length=150)),
                ('role', models.CharField(choices=[('DEVELOPER', 'Developer'), ('ARCHITECT', 'Software Architect'), ('MANAGER', 'Project Manager'), ('ADMIN', 'System Administrator'), ('ANALYST', 'Business Analyst'), ('TESTER', 'Quality Assurance Tester')], default='DEVELOPER', help_text='Professional role in the organization', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department or division within the company', max_length=100)),
                ('company_domain', models.CharField(help_text='Domain of the company (e.g., company.com)', max_length=100)),
                ('employee_id', models.CharField(blank=True, help_text='Company employee ID number', max_length=50, null=True, unique=True)),
                ('two_factor_secret', models.CharField(blank=True, help_text='Secret key for TOTP 2FA authentication', max_length=32)),
                ('is_2fa_enabled', models.BooleanField(default=False, help_text='Whether 2FA is enabled for this user')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed login attempts')),
                ('account_locked_until', models.DateTimeField(blank=True, help_text='Account is locked until this datetime', null=True)),
                ('password_changed_at', models.DateTimeField(auto_now_add=True, help_text='When password was last changed')),
                ('password_expires_at', models.DateTimeField(blank=True, help_text='When current password expires', null=True)),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='Backup codes for 2FA recovery')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last successful login', null=True)),
                ('last_login_user_agent', models.TextField(blank=True, help_text='User agent string of last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last profile update timestamp')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether corporate email has been verified')),
                ('email_verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=64)),
                ('last_activity', models.DateTimeField(blank=True, help_text='Last recorded user activity', null=True)),
                ('session_key', models.CharField(blank=True, help_text='Current session key', max_length=40)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Enterprise User',
                'verbose_name_plural': 'Enterprise Users',
                'db_table': 'enterprise_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Authorized domain (e.g., company.com)', max_length=255, unique=True)),
                ('company_name', models.CharField(help_text='Name of the company', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this domain is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When domain was added')),
                ('created_by', models.ForeignKey(help_text='User who added this domain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authorized Domain',
                'verbose_name_plural': 'Authorized Domains',
                'db_table': 'authorized_domains',
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(help_text='Hashed password', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this password was set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password History',
                'verbose_name_plural': 'Password History',
                'db_table': 'password_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='enterpriseuser',
            index=models.Index(fields=['corporate_email'], name='enterprise__corpora_12cc85_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseuser',
            index=models.Index(fields=['company_domain'], name='enterprise__company_9d94ec_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseuser',
            index=models.Index(fields=['role'], name='enterprise__role_8df708_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseuser',
            index=models.Index(fields=['is_active', 'email_verified'], name='enterprise__is_acti_c55298_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseuser',
            index=models.Index(fields=['created_at'], name='enterprise__created_e9e07a_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseuser',
            index=models.Index(fields=['last_login'], name='enterprise__last_lo_723c29_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizeddomain',
            index=models.Index(fields=['domain'], name='authorized__domain_b769f7_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizeddomain',
            index=models.Index(fields=['is_active'], name='authorized__is_acti_ea3be7_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['user', 'created_at'], name='password_hi_user_id_f4f4ce_idx'),
        ),
    ]
