# Generated by Django 5.0.7 on 2025-09-13 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizeddomain',
            options={'ordering': ['domain'], 'verbose_name': 'Authorized Domain', 'verbose_name_plural': 'Authorized Domains'},
        ),
        migrations.AlterModelOptions(
            name='enterpriseuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Enterprise User', 'verbose_name_plural': 'Enterprise Users'},
        ),
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Password History', 'verbose_name_plural': 'Password Histories'},
        ),
        migrations.RemoveIndex(
            model_name='enterpriseuser',
            name='enterprise__company_9d94ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterpriseuser',
            name='enterprise__is_acti_c55298_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterpriseuser',
            name='enterprise__created_e9e07a_idx',
        ),
        migrations.RenameIndex(
            model_name='authorizeddomain',
            new_name='accounts_au_domain_52e544_idx',
            old_name='authorized__domain_b769f7_idx',
        ),
        migrations.RenameIndex(
            model_name='authorizeddomain',
            new_name='accounts_au_is_acti_fe0941_idx',
            old_name='authorized__is_acti_ea3be7_idx',
        ),
        migrations.RenameIndex(
            model_name='enterpriseuser',
            new_name='accounts_en_corpora_a1bfcf_idx',
            old_name='enterprise__corpora_12cc85_idx',
        ),
        migrations.RenameIndex(
            model_name='enterpriseuser',
            new_name='accounts_en_role_56e583_idx',
            old_name='enterprise__role_8df708_idx',
        ),
        migrations.RenameIndex(
            model_name='enterpriseuser',
            new_name='accounts_en_last_lo_bc5cd0_idx',
            old_name='enterprise__last_lo_723c29_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordhistory',
            new_name='accounts_pa_user_id_d8ddd6_idx',
            old_name='password_hi_user_id_f4f4ce_idx',
        ),
        migrations.AddField(
            model_name='authorizeddomain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When domain was last updated'),
        ),
        migrations.AlterField(
            model_name='authorizeddomain',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who added this domain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_domains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enterpriseuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('DEVELOPER', 'Developer'), ('ANALYST', 'Business Analyst')], default='DEVELOPER', help_text='Professional role in the organization', max_length=20),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='password_hash',
            field=models.CharField(help_text='Hashed password for security comparison', max_length=128),
        ),
        migrations.AddIndex(
            model_name='authorizeddomain',
            index=models.Index(fields=['created_at'], name='accounts_au_created_760f03_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseuser',
            index=models.Index(fields=['is_2fa_enabled'], name='accounts_en_is_2fa__773afd_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseuser',
            index=models.Index(fields=['email_verified'], name='accounts_en_email_v_872882_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseuser',
            index=models.Index(fields=['password_expires_at'], name='accounts_en_passwor_9b04c5_idx'),
        ),
        migrations.AlterModelTable(
            name='authorizeddomain',
            table='accounts_authorized_domain',
        ),
        migrations.AlterModelTable(
            name='enterpriseuser',
            table='accounts_enterprise_user',
        ),
        migrations.AlterModelTable(
            name='passwordhistory',
            table='accounts_password_history',
        ),
    ]
