# Generated by Django 5.0.7 on 2025-09-20 02:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
        ('uml_diagrams', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation_type', models.CharField(choices=[('FULL_PROJECT', 'Full SpringBoot Project'), ('ENTITIES_ONLY', 'JPA Entities Only'), ('REPOSITORIES_ONLY', 'Repositories Only'), ('SERVICES_ONLY', 'Services Only'), ('CONTROLLERS_ONLY', 'Controllers Only'), ('CUSTOM', 'Custom Selection')], default='FULL_PROJECT', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('generation_config', models.JSONField(default=dict, help_text='SpringBoot project generation configuration')),
                ('selected_classes', models.JSONField(default=list, help_text='Selected UML classes for generation')),
                ('template_overrides', models.JSONField(default=dict, help_text='Custom template configurations')),
                ('output_path', models.CharField(blank=True, help_text='Generated files storage path', max_length=500)),
                ('download_url', models.URLField(blank=True, help_text='Temporary download URL for generated project')),
                ('download_expires_at', models.DateTimeField(blank=True, help_text='Download link expiration', null=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('progress_details', models.JSONField(default=dict, help_text='Detailed progress information')),
                ('error_details', models.JSONField(default=dict, help_text='Error information if generation failed')),
                ('generated_files_count', models.PositiveIntegerField(default=0)),
                ('generation_metadata', models.JSONField(default=dict, help_text='Additional generation metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to='uml_diagrams.umldiagram')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generation_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('GENERATION_STARTED', 'Generation Started'), ('GENERATION_COMPLETED', 'Generation Completed'), ('GENERATION_FAILED', 'Generation Failed'), ('GENERATION_CANCELLED', 'Generation Cancelled'), ('PROJECT_DOWNLOADED', 'Project Downloaded'), ('PROJECT_ARCHIVED', 'Project Archived'), ('PROJECT_DELETED', 'Project Deleted'), ('TEMPLATE_APPLIED', 'Template Applied'), ('CONFIG_UPDATED', 'Configuration Updated')], max_length=25)),
                ('action_details', models.JSONField(default=dict, help_text='Detailed information about the action')),
                ('execution_context', models.JSONField(default=dict, help_text='Context information when action was performed')),
                ('execution_duration', models.DurationField(blank=True, help_text='Duration of the action execution', null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_actions', to=settings.AUTH_USER_MODEL)),
                ('generation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='code_generation.generationrequest')),
            ],
            options={
                'db_table': 'generation_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True)),
                ('springboot_config', models.JSONField(help_text='Complete SpringBoot project configuration')),
                ('file_structure', models.JSONField(default=dict, help_text='Generated project file structure and metadata')),
                ('storage_path', models.CharField(help_text='File system path to generated project', max_length=500)),
                ('zip_file_path', models.CharField(blank=True, help_text='Path to compressed project archive', max_length=500)),
                ('zip_file_size', models.BigIntegerField(default=0)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('total_lines_of_code', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_projects', to='uml_diagrams.umldiagram')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_projects', to='projects.project')),
                ('generation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_project', to='code_generation.generationrequest')),
            ],
            options={
                'db_table': 'generated_projects',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('template_type', models.CharField(choices=[('ENTITY', 'JPA Entity'), ('REPOSITORY', 'Repository Interface'), ('SERVICE', 'Service Class'), ('CONTROLLER', 'REST Controller'), ('DTO', 'Data Transfer Object'), ('CONFIG', 'Configuration Class'), ('TEST', 'Test Class'), ('POM_XML', 'Maven POM'), ('APPLICATION_PROPERTIES', 'Application Properties'), ('MAIN_CLASS', 'Main Application Class')], max_length=25)),
                ('framework_version', models.CharField(choices=[('SPRING_BOOT_2', 'Spring Boot 2.x'), ('SPRING_BOOT_3', 'Spring Boot 3.x')], default='SPRING_BOOT_3', max_length=20)),
                ('template_content', models.TextField(help_text='Jinja2 template content')),
                ('default_variables', models.JSONField(default=dict, help_text='Default template variables and their values')),
                ('required_variables', models.JSONField(default=list, help_text='Required variables that must be provided')),
                ('output_filename_pattern', models.CharField(help_text='Pattern for generated file names (supports template variables)', max_length=255)),
                ('output_directory', models.CharField(help_text='Target directory for generated files', max_length=255)),
                ('file_extension', models.CharField(default='.java', max_length=10)),
                ('is_system_template', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_generation_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generation_templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['project', 'status'], name='generation__project_a14da7_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['requested_by', 'created_at'], name='generation__request_f6f203_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['status', 'created_at'], name='generation__status_11ff2a_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['diagram', 'generation_type'], name='generation__diagram_59294e_idx'),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['generation_request', 'timestamp'], name='generation__generat_5bc81d_idx'),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['performed_by', 'timestamp'], name='generation__perform_088b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['action_type', 'timestamp'], name='generation__action__50a2da_idx'),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['success', 'timestamp'], name='generation__success_16e271_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedproject',
            index=models.Index(fields=['project', 'status'], name='generated_p_project_54beac_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedproject',
            index=models.Index(fields=['generated_by', 'generated_at'], name='generated_p_generat_d747ba_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedproject',
            index=models.Index(fields=['diagram', 'status'], name='generated_p_diagram_6022a0_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedproject',
            index=models.Index(fields=['status', 'generated_at'], name='generated_p_status_837885_idx'),
        ),
        migrations.AddIndex(
            model_name='generationtemplate',
            index=models.Index(fields=['template_type', 'framework_version'], name='generation__templat_2b918d_idx'),
        ),
        migrations.AddIndex(
            model_name='generationtemplate',
            index=models.Index(fields=['is_system_template', 'is_active'], name='generation__is_syst_6f9280_idx'),
        ),
        migrations.AddIndex(
            model_name='generationtemplate',
            index=models.Index(fields=['created_by', 'created_at'], name='generation__created_0b4884_idx'),
        ),
        migrations.AddConstraint(
            model_name='generationtemplate',
            constraint=models.UniqueConstraint(fields=('name', 'template_type', 'framework_version'), name='unique_template_per_type_framework'),
        ),
    ]
