# Generated by Django 5.0.7 on 2025-09-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedproject',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedproject',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedproject',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
