# Generated by Django 5.0.7 on 2025-09-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generation', '0002_generatedproject_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedproject',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
