# Generated by Django 5.0.7 on 2025-09-13 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IPv4 or IPv6 address to whitelist', unique=True)),
                ('description', models.CharField(help_text='Description of this IP address or its purpose', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this IP whitelist entry is active')),
                ('access_level', models.CharField(choices=[('ADMIN', 'Admin Access'), ('API', 'API Access'), ('FULL', 'Full Access'), ('LIMITED', 'Limited Access')], default='LIMITED', help_text='Level of access granted to this IP', max_length=20)),
                ('allowed_paths', models.JSONField(blank=True, default=list, help_text='Specific paths this IP can access (empty = all paths)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this entry was created')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this IP was used for access', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this whitelist entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Whitelist Entry',
                'verbose_name_plural': 'IP Whitelist Entries',
                'db_table': 'security_ip_whitelist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(help_text='Name of the security setting', max_length=100, unique=True)),
                ('setting_value', models.TextField(help_text='Value of the security setting')),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this setting was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this setting was last updated')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this setting', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Configuration',
                'verbose_name_plural': 'Security Configurations',
                'db_table': 'security_configuration',
                'ordering': ['setting_name'],
            },
        ),
    ]
