# Generated by Django 5.0.7 on 2025-09-13 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityconfiguration',
            options={'ordering': ['category', 'setting_name'], 'verbose_name': 'Security Configuration', 'verbose_name_plural': 'Security Configurations'},
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='access_end_time',
            field=models.TimeField(blank=True, help_text='End time for daily access window', null=True),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='access_start_time',
            field=models.TimeField(blank=True, help_text='Start time for daily access window', null=True),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='allowed_countries',
            field=models.JSONField(blank=True, default=list, help_text='Country codes allowed for this IP (empty = all countries)'),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='blocked_paths',
            field=models.JSONField(blank=True, default=list, help_text='Specific paths this IP cannot access'),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='bypass_rate_limits',
            field=models.BooleanField(default=False, help_text='Whether this IP can bypass standard rate limits'),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this whitelist entry expires (null = never)', null=True),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='is_network_range',
            field=models.BooleanField(default=False, help_text='Whether this entry represents a network range (CIDR)'),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='is_trusted',
            field=models.BooleanField(default=False, help_text='Whether this IP is considered fully trusted'),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='last_user_agent',
            field=models.TextField(blank=True, help_text='Last user agent seen from this IP'),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='max_concurrent_sessions',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum concurrent sessions from this IP', null=True),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='max_requests_per_hour',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum requests per hour from this IP', null=True),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='network_mask',
            field=models.PositiveIntegerField(blank=True, help_text='Network mask for CIDR notation (e.g., 24 for /24)', null=True),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='requires_2fa',
            field=models.BooleanField(default=True, help_text='Whether users from this IP must use 2FA'),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='timezone_name',
            field=models.CharField(default='UTC', help_text='Timezone for time-based restrictions', max_length=50),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this entry was last updated'),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this IP has been used'),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='allowed_values',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed values (for enumerated types)'),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='category',
            field=models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('AUTHORIZATION', 'Authorization'), ('SESSION', 'Session Management'), ('RATE_LIMITING', 'Rate Limiting'), ('IP_SECURITY', 'IP Security'), ('PASSWORD_POLICY', 'Password Policy'), ('TWO_FACTOR', 'Two-Factor Authentication'), ('AUDIT', 'Audit & Logging'), ('EMAIL', 'Email Security'), ('API', 'API Security'), ('GENERAL', 'General Security')], default='GENERAL', help_text='Category of the security setting', max_length=30),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='change_reason',
            field=models.TextField(blank=True, help_text='Reason for the last change'),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this setting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_security_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='default_value',
            field=models.TextField(blank=True, help_text='Default value for this setting'),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='deployment_group',
            field=models.CharField(blank=True, help_text='Deployment group for this setting', max_length=100),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='environment',
            field=models.CharField(default='all', help_text='Target environment (production, staging, development, all)', max_length=50),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Whether this setting contains sensitive information'),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='is_system_setting',
            field=models.BooleanField(default=False, help_text='Whether this is a system setting (cannot be deleted)'),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='max_value',
            field=models.TextField(blank=True, help_text='Maximum allowed value (for numeric types)'),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='min_value',
            field=models.TextField(blank=True, help_text='Minimum allowed value (for numeric types)'),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='previous_value',
            field=models.TextField(blank=True, help_text='Previous value before last update'),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='requires_restart',
            field=models.BooleanField(default=False, help_text='Whether changing this setting requires application restart'),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='setting_type',
            field=models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON Object'), ('LIST', 'List'), ('FLOAT', 'Float')], default='STRING', help_text='Data type of the setting value', max_length=20),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='validation_regex',
            field=models.CharField(blank=True, help_text='Regular expression for value validation', max_length=500),
        ),
        migrations.AlterField(
            model_name='ipwhitelist',
            name='access_level',
            field=models.CharField(choices=[('ADMIN', 'Admin Access'), ('API', 'API Access'), ('FULL', 'Full Access'), ('LIMITED', 'Limited Access'), ('READONLY', 'Read-Only Access')], default='LIMITED', help_text='Level of access granted to this IP', max_length=20),
        ),
        migrations.AlterField(
            model_name='ipwhitelist',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this whitelist entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ip_whitelists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityconfiguration',
            name='setting_name',
            field=models.CharField(help_text='Unique name of the security setting', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='securityconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this setting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_security_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ipwhitelist',
            index=models.Index(fields=['ip_address'], name='security_ip_ip_addr_b3af78_idx'),
        ),
        migrations.AddIndex(
            model_name='ipwhitelist',
            index=models.Index(fields=['is_active', 'access_level'], name='security_ip_is_acti_fc678f_idx'),
        ),
        migrations.AddIndex(
            model_name='ipwhitelist',
            index=models.Index(fields=['expires_at'], name='security_ip_expires_6e35ed_idx'),
        ),
        migrations.AddIndex(
            model_name='ipwhitelist',
            index=models.Index(fields=['last_used'], name='security_ip_last_us_b1e161_idx'),
        ),
        migrations.AddIndex(
            model_name='securityconfiguration',
            index=models.Index(fields=['setting_name'], name='security_co_setting_548d60_idx'),
        ),
        migrations.AddIndex(
            model_name='securityconfiguration',
            index=models.Index(fields=['category', 'is_active'], name='security_co_categor_82d83b_idx'),
        ),
        migrations.AddIndex(
            model_name='securityconfiguration',
            index=models.Index(fields=['environment'], name='security_co_environ_403892_idx'),
        ),
        migrations.AddIndex(
            model_name='securityconfiguration',
            index=models.Index(fields=['is_system_setting'], name='security_co_is_syst_69a199_idx'),
        ),
    ]
