# Generated by Django 5.0.7 on 2025-09-20 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('uml_diagrams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HOST', 'Host'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer'), ('COMMENTER', 'Commenter')], default='EDITOR', max_length=15)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('cursor_position', models.JSONField(default=dict, help_text='Last known cursor position in diagram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_participants',
            },
        ),
        migrations.CreateModel(
            name='CollaborationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ENDED', 'Ended')], default='ACTIVE', max_length=10)),
                ('session_data', models.JSONField(default=dict, help_text='Session configuration and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_sessions', to='uml_diagrams.umldiagram')),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='collaboration_sessions', through='collaboration.CollaborationParticipant', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_sessions', to='projects.project')),
            ],
            options={
                'db_table': 'collaboration_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collaborationparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_detail', to='collaboration.collaborationsession'),
        ),
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ELEMENT_CREATED', 'Element Created'), ('ELEMENT_UPDATED', 'Element Updated'), ('ELEMENT_DELETED', 'Element Deleted'), ('ELEMENT_MOVED', 'Element Moved'), ('RELATIONSHIP_CREATED', 'Relationship Created'), ('RELATIONSHIP_UPDATED', 'Relationship Updated'), ('RELATIONSHIP_DELETED', 'Relationship Deleted'), ('ATTRIBUTE_ADDED', 'Attribute Added'), ('ATTRIBUTE_UPDATED', 'Attribute Updated'), ('ATTRIBUTE_REMOVED', 'Attribute Removed'), ('METHOD_ADDED', 'Method Added'), ('METHOD_UPDATED', 'Method Updated'), ('METHOD_REMOVED', 'Method Removed'), ('DIAGRAM_SAVED', 'Diagram Saved')], max_length=25)),
                ('element_id', models.CharField(help_text='ID of the affected UML element', max_length=100)),
                ('element_type', models.CharField(help_text='Type of UML element (class, interface, etc.)', max_length=50)),
                ('change_data', models.JSONField(help_text='Detailed change information and new values')),
                ('previous_data', models.JSONField(default=dict, help_text='Previous state for undo functionality')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_broadcasted', models.BooleanField(default=False)),
                ('broadcast_count', models.IntegerField(default=0)),
                ('sequence_number', models.BigIntegerField()),
                ('conflict_resolved', models.BooleanField(default=False)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='uml_diagrams.umldiagram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='collaboration.collaborationsession')),
            ],
            options={
                'db_table': 'collaboration_change_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DiagramLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lock_type', models.CharField(choices=[('ELEMENT', 'Element Lock'), ('ATTRIBUTE', 'Attribute Lock'), ('RELATIONSHIP', 'Relationship Lock'), ('SECTION', 'Section Lock')], default='ELEMENT', max_length=15)),
                ('element_id', models.CharField(help_text='ID of the locked UML element', max_length=100)),
                ('element_path', models.CharField(help_text='JSON path to the locked element/attribute', max_length=500)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('lock_metadata', models.JSONField(default=dict, help_text='Additional lock information and context')),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_locks', to='uml_diagrams.umldiagram')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='collaboration.collaborationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagram_locks',
                'ordering': ['acquired_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCursor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('viewport_zoom', models.FloatField(default=1.0)),
                ('viewport_center_x', models.FloatField(default=0.0)),
                ('viewport_center_y', models.FloatField(default=0.0)),
                ('selected_element_id', models.CharField(blank=True, help_text='Currently selected UML element ID', max_length=100)),
                ('cursor_color', models.CharField(default='#3B82F6', help_text='Hex color code for cursor display', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cursors', to='uml_diagrams.umldiagram')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cursors', to='collaboration.collaborationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursor_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_cursors',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.AddIndex(
            model_name='collaborationsession',
            index=models.Index(fields=['project', 'status'], name='collaborati_project_e903b7_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationsession',
            index=models.Index(fields=['diagram', 'created_at'], name='collaborati_diagram_82d6af_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationsession',
            index=models.Index(fields=['host_user', 'status'], name='collaborati_host_us_874fad_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationparticipant',
            index=models.Index(fields=['session', 'is_active'], name='collaborati_session_c21c71_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationparticipant',
            index=models.Index(fields=['user', 'joined_at'], name='collaborati_user_id_865158_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collaborationparticipant',
            unique_together={('session', 'user')},
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['session', 'timestamp'], name='collaborati_session_27918b_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['diagram', 'element_id'], name='collaborati_diagram_62c6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['user', 'timestamp'], name='collaborati_user_id_0c177c_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['sequence_number'], name='collaborati_sequenc_52c184_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['is_broadcasted', 'timestamp'], name='collaborati_is_broa_7bd996_idx'),
        ),
        migrations.AddIndex(
            model_name='diagramlock',
            index=models.Index(fields=['diagram', 'element_id', 'is_active'], name='diagram_loc_diagram_73c02f_idx'),
        ),
        migrations.AddIndex(
            model_name='diagramlock',
            index=models.Index(fields=['user', 'acquired_at'], name='diagram_loc_user_id_84ebd1_idx'),
        ),
        migrations.AddIndex(
            model_name='diagramlock',
            index=models.Index(fields=['session', 'is_active'], name='diagram_loc_session_50485c_idx'),
        ),
        migrations.AddIndex(
            model_name='diagramlock',
            index=models.Index(fields=['expires_at', 'is_active'], name='diagram_loc_expires_559c7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagramlock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('diagram', 'element_id', 'element_path'), name='unique_active_element_lock'),
        ),
        migrations.AddIndex(
            model_name='usercursor',
            index=models.Index(fields=['session', 'is_active'], name='user_cursor_session_f416e6_idx'),
        ),
        migrations.AddIndex(
            model_name='usercursor',
            index=models.Index(fields=['diagram', 'user'], name='user_cursor_diagram_379a02_idx'),
        ),
        migrations.AddIndex(
            model_name='usercursor',
            index=models.Index(fields=['last_updated'], name='user_cursor_last_up_53f7cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercursor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('session', 'user'), name='unique_active_user_cursor'),
        ),
    ]
