# Generated by Django 5.0.7 on 2025-09-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
