# Generated by Django 5.0.7 on 2025-09-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_collaborationsession_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationparticipant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=15),
        ),
    ]
