# Generated by Django 5.0.7 on 2025-11-08 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Flutter project UUID', primary_key=True, serialize=False)),
                ('diagram_id', models.UUIDField(db_index=True, help_text='UUID of UML diagram used to generate project')),
                ('session_id', models.CharField(db_index=True, help_text='Anonymous session ID of creator', max_length=64)),
                ('project_name', models.CharField(help_text='Project name in snake_case (e.g. erp_inventory)', max_length=200)),
                ('package_name', models.CharField(help_text='Package name (e.g. com.example.erp_inventory)', max_length=200)),
                ('config', models.JSONField(default=dict, help_text='Flutter project configuration')),
                ('metadata', models.JSONField(default=dict, help_text='Additional project metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_generated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'flutter_projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['diagram_id'], name='flutter_pro_diagram_a9ba1f_idx'), models.Index(fields=['session_id'], name='flutter_pro_session_c29de9_idx'), models.Index(fields=['created_at'], name='flutter_pro_created_18376d_idx'), models.Index(fields=['project_name'], name='flutter_pro_project_2ce46b_idx')],
            },
        ),
    ]
