# Generated by Django 5.0.7 on 2025-09-13 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('LOGOUT', 'User Logout'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('2FA_SUCCESS', '2FA Verification Success'), ('2FA_FAILED', '2FA Verification Failed'), ('BACKUP_CODE_USED', 'Backup Code Used'), ('ACCOUNT_CREATED', 'Account Created'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('EMAIL_VERIFIED', 'Email Verified'), ('PROFILE_UPDATED', 'Profile Updated'), ('SUSPICIOUS_LOGIN', 'Suspicious Login Detected'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt'), ('SESSION_HIJACK', 'Potential Session Hijacking'), ('ADMIN_LOGIN', 'Admin Login'), ('PERMISSION_GRANTED', 'Permission Granted'), ('PERMISSION_REVOKED', 'Permission Revoked'), ('DOMAIN_ADDED', 'Authorized Domain Added'), ('DOMAIN_REMOVED', 'Authorized Domain Removed'), ('API_ACCESS', 'API Access'), ('API_UNAUTHORIZED', 'Unauthorized API Access'), ('TOKEN_GENERATED', 'JWT Token Generated'), ('TOKEN_REVOKED', 'JWT Token Revoked')], help_text='Type of action performed', max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', help_text='Security severity level', max_length=10)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('session_key', models.CharField(blank=True, help_text='Session key if available', max_length=40)),
                ('resource', models.CharField(blank=True, help_text='Resource or endpoint accessed', max_length=200)),
                ('method', models.CharField(blank=True, help_text='HTTP method used', max_length=10)),
                ('status_code', models.PositiveIntegerField(blank=True, help_text='HTTP status code returned', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('country', models.CharField(blank=True, help_text='Country code based on IP', max_length=2)),
                ('city', models.CharField(blank=True, help_text='City based on IP', max_length=100)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for anonymous actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('BRUTE_FORCE', 'Brute Force Attack'), ('ACCOUNT_TAKEOVER', 'Account Takeover Attempt'), ('SUSPICIOUS_LOCATION', 'Login from Suspicious Location'), ('RATE_LIMITING', 'Rate Limit Violations'), ('MULTIPLE_FAILURES', 'Multiple Authentication Failures'), ('ANOMALOUS_BEHAVIOR', 'Anomalous User Behavior')], help_text='Type of security alert', max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', help_text='Current status of the alert', max_length=15)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Alert severity level', max_length=10)),
                ('title', models.CharField(help_text='Alert title/summary', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the security event')),
                ('risk_score', models.PositiveIntegerField(default=0, help_text='Calculated risk score (0-100)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the alert', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent if applicable')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the alert was resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the alert was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the alert was last updated')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the alert was resolved', null=True)),
                ('audit_logs', models.ManyToManyField(help_text='Audit logs that triggered this alert', related_name='security_alerts', to='audit.auditlog')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User associated with the alert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Alert',
                'verbose_name_plural': 'Security Alerts',
                'db_table': 'security_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='audit_logs_action__11f9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='audit_logs_ip_addr_932507_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'timestamp'], name='audit_logs_severit_549d29_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action_type'], name='audit_logs_user_id_f96629_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['status', 'severity'], name='security_al_status_9d0c83_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['user', 'created_at'], name='security_al_user_id_917922_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['alert_type', 'created_at'], name='security_al_alert_t_3110ff_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['risk_score'], name='security_al_risk_sc_bc3ca0_idx'),
        ),
    ]
