# Generated by Django 5.0.7 on 2025-09-13 04:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securityalert',
            name='affected_resources',
            field=models.JSONField(blank=True, default=list, help_text='List of resources affected by this security event'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Security analyst assigned to investigate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='confidence_score',
            field=models.PositiveIntegerField(default=50, help_text='Confidence in alert accuracy (0-100)'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='detection_rules',
            field=models.JSONField(blank=True, default=list, help_text='Detection rules that triggered this alert'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='first_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the suspicious activity was first detected'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityalert',
            name='investigation_notes',
            field=models.TextField(blank=True, help_text='Notes from security investigation'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the suspicious activity was last observed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='alert_type',
            field=models.CharField(choices=[('BRUTE_FORCE', 'Brute Force Attack'), ('ACCOUNT_TAKEOVER', 'Account Takeover Attempt'), ('SUSPICIOUS_LOCATION', 'Login from Suspicious Location'), ('RATE_LIMITING', 'Rate Limit Violations'), ('MULTIPLE_FAILURES', 'Multiple Authentication Failures'), ('ANOMALOUS_BEHAVIOR', 'Anomalous User Behavior'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation Attempt'), ('DATA_EXFILTRATION', 'Potential Data Exfiltration'), ('SESSION_ANOMALY', 'Session Anomaly Detected'), ('API_ABUSE', 'API Abuse Detected')], help_text='Type of security alert', max_length=30),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('ESCALATED', 'Escalated')], default='OPEN', help_text='Current status of the alert', max_length=15),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['assigned_to', 'status'], name='security_al_assigne_11e296_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['severity', 'status'], name='security_al_severit_1c570c_idx'),
        ),
    ]
